-- Custom SQL migration file, put your code below! --

-- ============================================================================
-- Migration: User-based licensing with encryption and recovery codes
-- Generated by: drizzle-kit generate --custom --name=figma_user_cleanup
-- Date: 2025-01-20
-- PRODUCTION SAFE: All operations use IF EXISTS/NOT EXISTS
-- ============================================================================

-- ============================================================================
-- STEP 1: Add new columns to licenses table for encryption and recovery codes
-- ============================================================================
ALTER TABLE "licenses"
ADD COLUMN IF NOT EXISTS "encrypted_key" text,
ADD COLUMN IF NOT EXISTS "recovery_codes" text DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "recovery_codes_used" text DEFAULT '[]';
--> statement-breakpoint

COMMENT ON COLUMN "licenses"."encrypted_key" IS 'AES-256-GCM encrypted license key for recovery purposes';
--> statement-breakpoint
COMMENT ON COLUMN "licenses"."recovery_codes" IS 'JSON array of hashed recovery codes (GitHub/Google standard)';
--> statement-breakpoint
COMMENT ON COLUMN "licenses"."recovery_codes_used" IS 'JSON array of used recovery codes with timestamps';
--> statement-breakpoint

-- ============================================================================
-- STEP 2: Rename device_id to figma_user_id in usage table
-- ============================================================================
ALTER TABLE "usage" RENAME COLUMN "device_id" TO "figma_user_id";
--> statement-breakpoint

DROP INDEX IF EXISTS "usage_device_idx";
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "usage_figma_user_idx" ON "usage" ("figma_user_id");
--> statement-breakpoint

COMMENT ON COLUMN "usage"."figma_user_id" IS 'Figma user ID for tracking free tier usage (no longer device-based)';
--> statement-breakpoint

-- ============================================================================
-- STEP 3: Convert existing license activations from deviceId to figmaUserId
-- This converts JSON like: {"deviceId": "figma-123"} -> {"figmaUserId": "123"}
-- ============================================================================
UPDATE "licenses"
SET "activations" = (
  SELECT COALESCE(
    jsonb_agg(
      CASE
        WHEN elem->>'deviceId' IS NOT NULL AND elem->>'deviceId' LIKE 'figma-%'
        THEN jsonb_build_object(
          'figmaUserId', REPLACE(elem->>'deviceId', 'figma-', ''),
          'activatedAt', elem->>'activatedAt',
          'lastChecked', elem->>'lastChecked'
        )
        WHEN elem->>'figmaUserId' IS NOT NULL
        THEN elem
        ELSE NULL
      END
    ) FILTER (WHERE
      (elem->>'deviceId' LIKE 'figma-%') OR
      (elem->>'figmaUserId' IS NOT NULL)
    ),
    '[]'::jsonb
  )::text
  FROM jsonb_array_elements(COALESCE("activations"::jsonb, '[]'::jsonb)) elem
)
WHERE "activations" IS NOT NULL
  AND "activations" != '[]'
  AND "activations"::text LIKE '%deviceId%';
--> statement-breakpoint

-- ============================================================================
-- STEP 4: Populate figma_user_id in licenses table from activations array
-- ============================================================================
UPDATE "licenses"
SET "figma_user_id" = (
  SELECT elem->>'figmaUserId'
  FROM jsonb_array_elements(COALESCE("activations"::jsonb, '[]'::jsonb)) elem
  WHERE elem->>'figmaUserId' IS NOT NULL
  LIMIT 1
)
WHERE "figma_user_id" IS NULL
  AND "activations" IS NOT NULL
  AND "activations" != '[]';
